language: scala
scala:
   - 2.10.4
   - 2.11.5
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7
script:
  - sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.11.5" && "${TRAVIS_JDK_VERSION}" == "oraclejdk7"' 
    tags: true
