language: scala
scala:
- 2.10.4
- 2.11.5
jdk:
- oraclejdk7
- openjdk6
- openjdk7
script:
- sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    tags: true
env:
  global:
  - secure: CMQoRlhW/ejJjiTIryucBgLXpbMOPx4tP9fzEKDpcltjQMZDIRyAezilraVXdI6Nap4BwbR+JuBXaG0wnfIR7hmEJe2EiWJoTWDXaHM2XnbPMsr44lXvDFPBm2H56jTf/yVTpp2HJO/iaeg+wMODPs9NqK974NY90WlwXuqIbZY=
  - secure: WuGBdY3IXh9RP2q0ffVy/Q/qDGTv/DOxjW8dG1BK6F21Itz+9O3cnqHlQtNsoVMB2FmpU3Gb66sOyOYsbE4FDNB+RkFZ+bQ5qlYwNtqea6IgyODWFYMf/6+BxlyEKyFo45BHF33TIZet37vVWx9qdDPaN0tZ8fV5+gwtUa4BJ44=
